// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://oolldeqohytwmibqaiiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vbGxkZXFvaHl0d21pYnFhaWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzQ4MjgsImV4cCI6MjA2NTc1MDgyOH0.nQ1mLtLVRBbPA3fHtF7ZOCFXoVRNy9Bb2liSvHOEf9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);